name: Build and Push Docker Image

run-name: Docker GHCR - ${{ github.sha }}

on:
  push:
    branches:
      - feature/laravel-crud
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/kepl2026/evolusi-pl-24-535556-sv-24264:${{ github.sha }}